version: "3.3"
services:

  api:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/app/
    ports:
      - "8000:80"
    networks:
      - local
    command: "/app/bootstrap/docker/start_api.sh"

networks:
  local:
    external: true
