name: Publish Docker

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Login to GitHub Package Registry
        run: docker login docker.pkg.github.com -u ${{ secrets.username }} -p ${{ secrets.password }}
      - uses: actions/checkout@develop
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: recipe-api
          username: ${{ secrets.username }}
          password: ${{ secrets.password }}
          registry: docker.pkg.github.com
