name: Publish and Deploy Docker

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: codefingers/recipe/recipe_api:1
          username: $GITHUB_ACTOR
          password: ${{ secrets.password }}
          registry: docker.pkg.github.com
      - name: Deploy to Droplet
        run: ssh root@${{ secrets.serverpass }} && ls -la
