name: Publish and Deploy Docker

on:
  push:
    branches:
      - '*'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: codefingers/recipe/recipe_api:1
          username: $GITHUB_ACTOR
          password: ${{ secrets.password }}
          registry: docker.pkg.github.com
          buildargs: mysqlhost={{ secrets.mysqlhost }},mysqldb={{ secrets.mysqldb }},mysqluser={{ secrets.mysqluser }},mysqlpass={{ secrets.mysqlpass }}
      - name: SSH to Droplet
        uses: appleboy/ssh-action@master
        env:
          MYSQLHOST: {{ secrets.mysqlhost }}
          MYSQLDB: {{ secrets.mysqldb }}
          MSYQLUSER: {{ secrets.mysqluser }}
          MYSQLPASS: {{ secrets.mysqlpass }}
        with:
          host: ${{ secrets.serverhost }}
          username: ${{ secrets.serveruser }}
          key: ${{ secrets.serverpass }}
          script: |
            cd /var/www/Recipe
            docker pull docker.pkg.github.com/codefingers/recipe/recipe_api:1
            docker stop recipe_api
            docker container prune -f
            docker run -d --name recipe_api -p 8000:80 docker.pkg.github.com/codefingers/recipe/recipe_api:1
            docker exec -i recipe_api bash << EOF\n sed 's/DB_HOST=/DB_HOST=$MYSQLHOST/' .env\n EOF
